import Nav from "@/components/Nav";
import CursorProvider from "./context/CursorProvider";
import "./globals.css";
import { Manrope } from "next/font/google";
import AppWrapper from "@/components/AppWrapper";
import AnimationAndLogicProvider from "./context/AnimationAndLogicProvider";
import LenisProvider from "./context/LenisProvider";
import Footer from "@/components/HomeParts/Footer";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { Toaster } from "react-hot-toast";


const manropeFont = Manrope({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Karan Mohan Talwar | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${manropeFont.className} antialiased bg-[#18181B]`}>
        <ReactQueryProvider>
        <AnimationAndLogicProvider>
          <LenisProvider>
          <CursorProvider>
<Toaster
          position="top-right"
          reverseOrder={false}
          gutter={10}
          toastOptions={{
            duration: 3000,
            style: {
              background: "#0f0f0f",
              color: "#fff",
              borderRadius: "14px",
              padding: "14px 18px",
              fontSize: "14px",
              boxShadow: "0 10px 30px rgba(0,0,0,0.2)",
            },
            success: {
              iconTheme: {
                primary: "#22c55e",
                secondary: "#0f0f0f",
              },
            },
            error: {
              iconTheme: {
                primary: "#ef4444",
                secondary: "#0f0f0f",
              },
            },
          }}
        />
            {/* Page content with loader control */}
            <AppWrapper>{children}</AppWrapper>
        <Footer />
          </CursorProvider>
          </LenisProvider>
        </AnimationAndLogicProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
