import Nav from "@/components/Nav";
import CursorProvider from "./context/CursorProvider";
import "./globals.css";
import { Manrope } from "next/font/google";
import AppWrapper from "@/components/AppWrapper";
import AnimationAndLogicProvider from "./context/AnimationAndLogicProvider";
import LenisProvider from "./context/LenisProvider";
import Footer from "@/components/HomeParts/Footer";


const manropeFont = Manrope({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Karan Mohan Talwar | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${manropeFont.className} antialiased bg-[#18181B]`}>
        <AnimationAndLogicProvider>
          <LenisProvider>
          <CursorProvider>

            {/* Page content with loader control */}
            <AppWrapper>{children}</AppWrapper>
          <Footer />
          </CursorProvider>
          </LenisProvider>
        </AnimationAndLogicProvider>
      </body>
    </html>
  );
}
